import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const architecture = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/architecture' }),
  schema: z.object({
    title: z.string(),
    year: z.string(),
    type: z.string(),
    typeEs: z.string().optional(),
    location: z.string(),
    locationEs: z.string().optional(),
    area: z.string(),
    budget: z.string().optional(),
    duration: z.string(),
    durationEs: z.string().optional(),
    status: z.string(),
    statusEs: z.string().optional(),
    role: z.string(),
    roleEs: z.string().optional(),
    resumen: z.string(),
    resumenEs: z.string().optional(),
    heroColor: z.string(),
    photos: z.array(z.string()),
    gallery: z.array(z.string()).optional(),
    descriptionEn: z.array(z.string()).optional(),
    descriptionEs: z.array(z.string()).optional(),
    firm: z.string().optional(),
    results: z.array(z.object({ value: z.string(), label: z.string() })).optional(),
    resultsEs: z.array(z.object({ value: z.string(), label: z.string() })).optional(),
    skills: z.array(z.string()).optional(),
    isPM: z.boolean().optional(),
    order: z.number(),
  }),
});

const apps = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/apps' }),
  schema: z.object({
    name: z.string(),
    status: z.enum(['live', 'dev']),
    statusLabel: z.string(),
    statusLabelEs: z.string().optional(),
    year: z.string(),
    platform: z.string(),
    tags: z.array(z.string()),
    resumen: z.string(),
    resumenEs: z.string().optional(),
    tagline: z.string(),
    taglineEs: z.string().optional(),
    bg: z.string(),
    heroColor: z.string().optional(),
    letter: z.string(),
    tech: z.array(z.object({ category: z.string(), items: z.string() })).optional(),
    features: z.array(z.string()).optional(),
    featuresEs: z.array(z.string()).optional(),
    statusNote: z.string().optional(),
    statusNoteEs: z.string().optional(),
    appStoreUrl: z.string().nullable().optional(),
    webUrl: z.string().nullable().optional(),
    order: z.number(),
  }),
});

export const collections = { architecture, apps };
